INSERT INTO assets (
    asset_tag, 
    name, 
    brand, 
    description, 
    status, 
    version, 
    created_at, 
    updated_at
) VALUES 
-- Laptops & Workstations
('LAP-001', 'MacBook Pro 16" M3 Max', 'Apple', 'Space Black, 36GB RAM, 1TB SSD - Engineering Fleet', 'AVAILABLE', 0, NOW(), NOW()),
('LAP-002', 'MacBook Pro 14" M3 Pro', 'Apple', 'Silver, 18GB RAM, 512GB SSD - Product Design Team', 'AVAILABLE', 0, NOW(), NOW()),
('LAP-003', 'MacBook Air 15" M2', 'Apple', 'Midnight, 16GB RAM, 512GB SSD - Marketing Team', 'UNAVAILABLE', 0, NOW(), NOW()),
('LAP-004', 'ThinkPad X1 Carbon Gen 11', 'Lenovo', 'Intel i7-1370P, 32GB RAM, 1TB SSD - Executive Fleet', 'AVAILABLE', 0, NOW(), NOW()),
('LAP-005', 'ThinkPad T14s Gen 4', 'Lenovo', 'AMD Ryzen 7 PRO, 16GB RAM, 512GB SSD - Sales Fleet', 'AVAILABLE', 0, NOW(), NOW()),
('LAP-006', 'ThinkPad P1 Gen 6', 'Lenovo', 'Intel i9-13900H, 64GB RAM, RTX 4080 - Mobile Workstation', 'DAMAGED', 0, NOW(), NOW()),
('LAP-007', 'Dell XPS 15 9530', 'Dell', 'Intel i9-13900H, 32GB RAM, RTX 4060 - QA Test Station', 'AVAILABLE', 0, NOW(), NOW()),
('LAP-008', 'Dell Latitude 7440', 'Dell', 'Intel i5-1345U, 16GB RAM, 256GB SSD - Operations Fleet', 'UNAVAILABLE', 0, NOW(), NOW()),
('LAP-009', 'Dell Precision 7680', 'Dell', 'Intel i7-13850HX, 32GB RAM, RTX A2000 - CAD/3D Modeling', 'AVAILABLE', 0, NOW(), NOW()),
('LAP-010', 'HP EliteBook 840 G10', 'HP', 'Intel i7-1360P, 16GB RAM, 512GB SSD - HR Fleet', 'AVAILABLE', 0, NOW(), NOW()),
('LAP-011', 'HP ZBook Studio G10', 'HP', 'Intel i7-13700H, 32GB RAM, RTX 4070 - Video Production', 'AVAILABLE', 0, NOW(), NOW()),
('LAP-012', 'ASUS ROG Zephyrus G14', 'ASUS', 'AMD Ryzen 9, 32GB RAM, RTX 4070 - AR/VR Test Rig', 'DAMAGED', 0, NOW(), NOW()),
('LAP-013', 'MacBook Air 13" M2', 'Apple', 'Starlight, 8GB RAM, 256GB SSD - Intern Fleet', 'AVAILABLE', 0, NOW(), NOW()),
('LAP-014', 'ThinkPad L14 Gen 4', 'Lenovo', 'Intel i5-1335U, 16GB RAM, 512GB SSD - Support Team', 'UNAVAILABLE', 0, NOW(), NOW()),
('LAP-015', 'Dell Latitude 5540', 'Dell', 'Intel i7-1355U, 16GB RAM, 512GB SSD - Finance Fleet', 'AVAILABLE', 0, NOW(), NOW()),

-- Desktop Computers & Mini PCs
('DT-001', 'Mac Studio M2 Ultra', 'Apple', '64GB RAM, 1TB SSD - Main Video Editing Bay', 'AVAILABLE', 0, NOW(), NOW()),
('DT-002', 'Mac mini M2 Pro', 'Apple', '16GB RAM, 512GB SSD - CI/CD Build Node A', 'AVAILABLE', 0, NOW(), NOW()),
('DT-003', 'Mac mini M2 Pro', 'Apple', '16GB RAM, 512GB SSD - CI/CD Build Node B', 'AVAILABLE', 0, NOW(), NOW()),
('DT-004', 'Dell OptiPlex 7010 Micro', 'Dell', 'Intel i5-13500T, 16GB RAM - Front Desk Station 1', 'AVAILABLE', 0, NOW(), NOW()),
('DT-005', 'Dell OptiPlex 7010 Micro', 'Dell', 'Intel i5-13500T, 16GB RAM - Front Desk Station 2', 'UNAVAILABLE', 0, NOW(), NOW()),
('DT-006', 'HP Elite Mini 800 G9', 'HP', 'Intel i7-13700T, 32GB RAM - Conference Room PC', 'AVAILABLE', 0, NOW(), NOW()),
('DT-007', 'Custom AI Workstation', 'Custom', 'Dual RTX 4090, Threadripper PRO, 128GB RAM - AI R&D', 'AVAILABLE', 0, NOW(), NOW()),
('DT-008', 'Lenovo ThinkCentre M90q', 'Lenovo', 'Intel i7-13700, 32GB RAM - Security Operations', 'AVAILABLE', 0, NOW(), NOW()),

-- Displays & Monitors
('MON-001', 'Dell UltraSharp 27 4K (U2723QE)', 'Dell', '27-inch IPS USB-C Hub Monitor - Desk A1', 'AVAILABLE', 0, NOW(), NOW()),
('MON-002', 'Dell UltraSharp 27 4K (U2723QE)', 'Dell', '27-inch IPS USB-C Hub Monitor - Desk A2', 'AVAILABLE', 0, NOW(), NOW()),
('MON-003', 'Dell UltraSharp 27 4K (U2723QE)', 'Dell', '27-inch IPS USB-C Hub Monitor - Desk A3', 'UNAVAILABLE', 0, NOW(), NOW()),
('MON-004', 'Dell UltraSharp 27 4K (U2723QE)', 'Dell', '27-inch IPS USB-C Hub Monitor - Desk A4', 'AVAILABLE', 0, NOW(), NOW()),
('MON-005', 'Dell UltraSharp 34 Curved (U3423WE)', 'Dell', '34-inch UWQHD Curved USB-C Hub - Exec Suite 1', 'AVAILABLE', 0, NOW(), NOW()),
('MON-006', 'Dell UltraSharp 34 Curved (U3423WE)', 'Dell', '34-inch UWQHD Curved USB-C Hub - Exec Suite 2', 'AVAILABLE', 0, NOW(), NOW()),
('MON-007', 'Apple Studio Display 27"', 'Apple', '5K Retina Display with Tilt Stand - Design Bay 1', 'AVAILABLE', 0, NOW(), NOW()),
('MON-008', 'Apple Studio Display 27"', 'Apple', '5K Retina Display with Tilt Stand - Design Bay 2', 'DAMAGED', 0, NOW(), NOW()),
('MON-009', 'Apple Pro Display XDR 32"', 'Apple', '6K Retina Display with Pro Stand - Color Grading', 'AVAILABLE', 0, NOW(), NOW()),
('MON-010', 'LG UltraFine 27US500-W', 'LG', '27-inch 4K UHD Display - Overflow Desk 1', 'AVAILABLE', 0, NOW(), NOW()),
('MON-011', 'LG UltraFine 27US500-W', 'LG', '27-inch 4K UHD Display - Overflow Desk 2', 'AVAILABLE', 0, NOW(), NOW()),
('MON-012', 'HP Z27k G3 4K', 'HP', '27-inch USB-C IPS Ergonomic Monitor - Dev Station', 'UNAVAILABLE', 0, NOW(), NOW()),
('MON-013', 'Samsung Odyssey G9 49"', 'Samsung', 'Dual-QHD 240Hz Curved Gaming Monitor - Demo Room', 'AVAILABLE', 0, NOW(), NOW()),
('MON-014', 'BenQ DesignVue PD3220U', 'BenQ', '32-inch 4K Thunderbolt 3 Designer Monitor', 'AVAILABLE', 0, NOW(), NOW()),
('MON-015', 'ASUS ProArt PA279CV', 'ASUS', '27-inch 4K UHD Color Accurate Monitor', 'AVAILABLE', 0, NOW(), NOW()),

-- Mobile & Tablet Devices
('TAB-001', 'iPad Pro 12.9" M2', 'Apple', 'Wi-Fi 256GB Space Gray - Exec Sign-off Kit', 'AVAILABLE', 0, NOW(), NOW()),
('TAB-002', 'iPad Pro 11" M2', 'Apple', 'Cellular 128GB Silver - Field Operations 1', 'UNAVAILABLE', 0, NOW(), NOW()),
('TAB-003', 'iPad Air 10.9" M1', 'Apple', 'Wi-Fi 64GB Blue - Kiosk Station A', 'AVAILABLE', 0, NOW(), NOW()),
('TAB-004', 'iPad Air 10.9" M1', 'Apple', 'Wi-Fi 64GB Blue - Kiosk Station B', 'AVAILABLE', 0, NOW(), NOW()),
('TAB-005', 'Samsung Galaxy Tab S9 Ultra', 'Galaxy', '512GB Graphite with S Pen - Mobile Testing', 'DAMAGED', 0, NOW(), NOW()),
('TAB-006', 'Microsoft Surface Pro 9', 'Microsoft', 'Intel i7, 16GB RAM, 256GB SSD - Sales Demo Unit', 'AVAILABLE', 0, NOW(), NOW()),
('PHN-001', 'iPhone 15 Pro Max', 'Apple', '256GB Natural Titanium - iOS Test Device A', 'AVAILABLE', 0, NOW(), NOW()),
('PHN-002', 'iPhone 14', 'Apple', '128GB Midnight - iOS Test Device B', 'UNAVAILABLE', 0, NOW(), NOW()),
('PHN-003', 'Google Pixel 8 Pro', 'Google', '128GB Obsidian - Android Test Device A', 'AVAILABLE', 0, NOW(), NOW()),
('PHN-004', 'Samsung Galaxy S24 Ultra', 'Samsung', '256GB Titanium Gray - Android Test Device B', 'AVAILABLE', 0, NOW(), NOW()),

-- Networking & Infrastructure
('NET-001', 'Cisco Catalyst 9300 Switch', 'Cisco', '48-Port PoE+ Managed Switch - Server Rack A', 'AVAILABLE', 0, NOW(), NOW()),
('NET-002', 'Cisco Catalyst 9300 Switch', 'Cisco', '48-Port PoE+ Managed Switch - Server Rack B', 'AVAILABLE', 0, NOW(), NOW()),
('NET-003', 'UniFi Dream Machine SE', 'Ubiquiti', 'Enterprise Gateway & Network Controller - Main HQ', 'AVAILABLE', 0, NOW(), NOW()),
('NET-004', 'UniFi Swiss Army WiFi 6 AP', 'Ubiquiti', 'Long-Range Enterprise Access Point - Floor 1 North', 'AVAILABLE', 0, NOW(), NOW()),
('NET-005', 'UniFi Swiss Army WiFi 6 AP', 'Ubiquiti', 'Long-Range Enterprise Access Point - Floor 1 South', 'AVAILABLE', 0, NOW(), NOW()),
('NET-006', 'UniFi Swiss Army WiFi 6 AP', 'Ubiquiti', 'Long-Range Enterprise Access Point - Floor 2 North', 'UNAVAILABLE', 0, NOW(), NOW()),
('NET-007', 'Palo Alto PA-440 Firewall', 'Palo Alto', 'Next-Gen Firewall Security Appliance - Perimeter', 'AVAILABLE', 0, NOW(), NOW()),
('NET-008', 'Synology DiskStation DS1821+', 'Synology', '8-Bay NAS System 64TB - On-Premises Backup', 'AVAILABLE', 0, NOW(), NOW()),
('NET-009', 'APC Smart-UPS RT 3000VA', 'APC', 'On-Line Power Backup - Main Server Rack', 'AVAILABLE', 0, NOW(), NOW()),
('NET-010', 'MikroTik CCR2004 Router', 'MikroTik', '12x SFP+ 10G Cloud Core Router - Lab Network', 'DAMAGED', 0, NOW(), NOW()),

-- Peripherals, Audio & Accessories
('ACC-001', 'Logitech MX Master 3S', 'Logitech', 'Wireless Performance Mouse - Desk A1', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-002', 'Logitech MX Master 3S', 'Logitech', 'Wireless Performance Mouse - Desk A2', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-003', 'Logitech MX Keys S', 'Logitech', 'Wireless Illuminated Keyboard - Desk A1', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-004', 'Logitech MX Keys S', 'Logitech', 'Wireless Illuminated Keyboard - Desk A2', 'UNAVAILABLE', 0, NOW(), NOW()),
('ACC-005', 'Keychron Q1 Pro Mechanical', 'Keychron', 'QMK/VIA Wireless Custom Keyboard - Dev Pool', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-006', 'Apple Magic Keyboard with Touch ID', 'Apple', 'Wireless Keyboard with Numeric Keypad', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-007', 'Apple Magic Trackpad', 'Apple', 'Black Surface Multi-Touch Trackpad', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-008', 'Logitech Brio 4K Webcam', 'Logitech', 'Ultra HD Webcam with HDR & RightLight 3 - Conf Room A', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-009', 'Logitech Brio 4K Webcam', 'Logitech', 'Ultra HD Webcam with HDR & RightLight 3 - Conf Room B', 'UNAVAILABLE', 0, NOW(), NOW()),
('ACC-010', 'Elgato Stream Deck XL', 'Elgato', '32 Macro Keys Studio Controller - Media Room', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-011', 'CalDigit TS4 Thunderbolt 4 Dock', 'CalDigit', '18 Ports, 98W Charging - Hot Desk Station 1', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-012', 'CalDigit TS4 Thunderbolt 4 Dock', 'CalDigit', '18 Ports, 98W Charging - Hot Desk Station 2', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-013', 'Anker 778 Thunderbolt 4 Dock', 'Anker', '12-in-1 Dual Display Dock - Hot Desk Station 3', 'DAMAGED', 0, NOW(), NOW()),
('ACC-014', 'Rode Rodecaster Pro II', 'Rode', 'Integrated Audio Production Studio - Podcast Studio', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-015', 'Shure SM7B Dynamic Mic', 'Shure', 'Vocal Microphone - Podcast Studio Mic 1', 'AVAILABLE', 0, NOW(), NOW()),
('ACC-016', 'Shure SM7B Dynamic Mic', 'Shure', 'Vocal Microphone - Podcast Studio Mic 2', 'AVAILABLE', 0, NOW(), NOW()),
('AUD-001', 'Bose QuietComfort Ultra', 'Bose', 'Noise Canceling Bluetooth Headphones - Executive', 'UNAVAILABLE', 0, NOW(), NOW()),
('AUD-002', 'Sony WH-1000XM5', 'Sony', 'Wireless Noise Canceling Headphones - Engineering', 'AVAILABLE', 0, NOW(), NOW()),
('AUD-003', 'Jabra Evolve2 85 UC', 'Jabra', 'Wireless Stereo Headset - Support Lead', 'AVAILABLE', 0, NOW(), NOW()),
('AUD-004', 'Jabra Speak2 75 Speakerphone', 'Jabra', 'Wireless Conference Speakerphone - Huddle Room 1', 'AVAILABLE', 0, NOW(), NOW()),

-- AV & Conference Room Gear
('AV-001', 'Neat Bar Pro Conference System', 'Neat', 'Video Bar with Touch Controller - Boardroom', 'AVAILABLE', 0, NOW(), NOW()),
('AV-002', 'Logitech Rally Plus System', 'Logitech', 'Ultra-HD Modular Video Conferencing - Conf Room Main', 'AVAILABLE', 0, NOW(), NOW()),
('AV-003', 'Epson Pro EX11000 Projector', 'Epson', 'Full HD 1080p Wireless Laser Projector - All-Hands Hall', 'AVAILABLE', 0, NOW(), NOW()),
('AV-004', 'Samsung 75" QLED 4K Smart TV', 'Samsung', 'Commercial Display QB75B - Main Lobby', 'AVAILABLE', 0, NOW(), NOW()),
('AV-005', 'Samsung 65" QLED 4K Smart TV', 'Samsung', 'Commercial Display QB65B - Executive Conf Room', 'UNAVAILABLE', 0, NOW(), NOW()),
('AV-006', 'Poly Studio X50 Video Bar', 'Poly', 'All-in-One Video Bar with TC8 Touch Pad - Huddle Room 2', 'AVAILABLE', 0, NOW(), NOW()),

-- Printers & Office Equipment
('PRN-001', 'HP Color LaserJet Enterprise M555x', 'HP', 'Duplex Color Network Printer - Print Room 1', 'AVAILABLE', 0, NOW(), NOW()),
('PRN-002', 'Canon ImageRUNNER ADVANCE DX C3835i', 'Canon', 'Multifunction Enterprise Copier/Scanner - Mailroom', 'AVAILABLE', 0, NOW(), NOW()),
('PRN-003', 'Brother HL-L6400DW Monochrome', 'Brother', 'High-Volume Enterprise Monochrome Printer - Finance', 'DAMAGED', 0, NOW(), NOW()),
('PRN-004', 'Zebra ZT411 Industrial Label Printer', 'Zebra', 'Barcode & Asset Tag Label Thermal Printer - Warehouse', 'AVAILABLE', 0, NOW(), NOW()),
('PRN-005', 'Dymo LabelWriter 5XL', 'Dymo', 'Wide-Format Shipping Label Printer - Mailroom', 'AVAILABLE', 0, NOW(), NOW()),

-- Testing, Specialized & VR Hardware
('TST-001', 'Meta Quest 3 512GB', 'Meta', 'MR Headset with Touch Plus Controllers - R&D Lab', 'AVAILABLE', 0, NOW(), NOW()),
('TST-002', 'Apple Vision Pro 512GB', 'Apple', 'Spatial Computer Headset - Spatial App R&D', 'AVAILABLE', 0, NOW(), NOW()),
('TST-003', 'HTC Vive Pro 2 System', 'HTC', 'VR Headset with Base Stations - Simulation Lab', 'UNAVAILABLE', 0, NOW(), NOW()),
('TST-004', 'Fluke 87V Industrial Multimeter', 'Fluke', 'Digital Multimeter - Electrical Engineering Bench', 'AVAILABLE', 0, NOW(), NOW()),
('TST-005', 'Rigol DS1054Z Oscilloscope', 'Rigol', '50MHz Digital Oscilloscope 4 Channels - Hardware Lab', 'AVAILABLE', 0, NOW(), NOW()),
('TST-006', 'Saleae Logic Pro 16', 'Saleae', '16 Channel Logic Analyzer - Hardware Debugging', 'AVAILABLE', 0, NOW(), NOW()),
('TST-007', 'Raspberry Pi 4 Model B (8GB)', 'Raspberry Pi', 'Embedded Test Node A - Server Room', 'AVAILABLE', 0, NOW(), NOW()),
('TST-008', 'Raspberry Pi 4 Model B (8GB)', 'Raspberry Pi', 'Embedded Test Node B - Server Room', 'AVAILABLE', 0, NOW(), NOW()),
('TST-009', 'NVIDIA Jetson AGX Orin 64GB', 'NVIDIA', 'Developer Kit for Edge AI Application Testing', 'AVAILABLE', 0, NOW(), NOW()),
('TST-010', 'HackRF One Software Defined Radio', 'Great Scott Gadgets', 'SDR Transceiver 1MHz to 6GHz - Security Audit Kit', 'AVAILABLE', 0, NOW(), NOW()),

-- Miscellaneous Facilities & Office Fleet
('FAC-001', 'Ecovacs Deebot X2 Omni', 'Ecovacs', 'Robotic Vacuum & Mop Cleaner - Executive Floor', 'AVAILABLE', 0, NOW(), NOW()),
('FAC-002', 'Fellowes AutoMax 200C Shredder', 'Fellowes', 'Cross-Cut Auto Feed Shredder - HR Office', 'AVAILABLE', 0, NOW(), NOW()),
('FAC-003', 'Dyson Purifier Cool TP07', 'Dyson', 'Smart Air Purifier Fan - Main Conference Room', 'AVAILABLE', 0, NOW(), NOW()),
('FAC-004', 'Breville Oracle Touch Espresso Machine', 'Breville', 'Automatic Coffee/Espresso Station - Employee Lounge', 'UNAVAILABLE', 0, NOW(), NOW()),
('FAC-005', 'Segway Ninebot Max G30P Electric Scooter', 'Segway', 'Campus Commuter Scooter Unit 1 - Facilities', 'AVAILABLE', 0, NOW(), NOW());